src/app.js, src/validateForm.js, src/views/chooseLocation.njk
-  Creates chooseLocation.njk file and defines a route for it in the app.js file
- Introduces a select component to chooseLocation file .
-  Implements error handling for the select form.
-  Redirects to the home page when the user enters text and clicks continue since the manage form submission page is not yet created.
- Modified the generic validateForm function so that it could still be used for select form as form has a default value selected on load.
(DFC-45)[https://govukverify.atlassian.net/browse/DFC-45]
1. Navigate to /choose-location page
2. Test the error handling of the form.
3. Verify the redirection functionality to the home page when item is selected.
Saving data from form entry will be added later/ another ticket
=> DFC-45 | GA4 | Sandbox | Create form - select component on test page

package-lock.json, package.json, src/views/common/base.njk
Updated package to the latest version and added page view tracker call on the base.njk file after initialisation to test .
(DFC-64)[https://govukverify.atlassian.net/browse/DFC-64]
Tracker is called on all pages but there seems to be an issue with the google tag loading when I navigate from home page to other pages. Screenshots below 
**Home Page**
**Organisational Type Page**
=> DFC|GA4|Test tracker function in demo app

src/views/home.njk
Adds Generic Inbound and Outbound Link 
(DFC-126)[https://govukverify.atlassian.net/browse/DFC-126]
=> DFC-126 | GA4 | Add generic navigation links to demo app

package-lock.json, package.json
- Upgrades package to latest version
- Tested the navigationTracker fired for generic inbound and outbound links found on the home page
(DFC-88)[https://govukverify.atlassian.net/browse/DFC-88]
Review Screenshots
NavigationTracker is fired for both Generic Inbound and Outbound Links , see screenshots below . 
**Inbound Link**
**Outbound Link**
=> DFC-88-Test-Tracker-Function-In-Demo-App

src/app.js, src/config/constants.js, src/config/gtmMiddleware.js, src/views/common/base.njk, src/views/helpWithHint.njk, src/views/serviceDescription.njk
- Adds a middleware file.
-Sets the GA4 Container ID in res.locals for universal accessibility.Eliminates the need to repeat GA4 Container ID in every route. 
- Dynamically sets the HTTP status code for the On Page Load tracker instead of being hardcoded in the base.njk file.
- Dynamically sets values for taxonomy levels 1 and 2 for the On Page Load tracker instead of being hardcoded in the base.njk file.
(DFC-132)[https://govukverify.atlassian.net/browse/DFC-132]
Check that the google tag is being loaded on all pages including the error pages.
=> DFC-132-need-to-create-middleware-functions-able-to-inject-render-options

src/views/common/base.njk
(DFC-140)[https://govukverify.atlassian.net/browse/DFC-140]
Users will be able to see the alpha phase banner at the top of every page
- inbound link included
- outbound link included
=> Dfc 140 add a phase banner into our demo app

src/app.js, src/config/constants.js, src/config/gtmMiddleware.js, src/config/middleware.js, src/views/home.njk, src/views/journeyGuard.njk, src/views/organisationType.njk
I have used express session to implement the journey guard.
- Adds middleware function that that checks if user is on the home page and does not have an active session, and sets a session value if true, if user is not on the home page and does not have a session value then they are redirected to Journey Guard Page which has a link which the user can click to take them to Home Page where session is set and they are able to navigate freely.
- Adds middleware.js file for this function
- Uses middleware function in app.js file
- Changes path for home page from `/ `to` /welcome` to fix bug I was facing .
(DFC-63)[https://govukverify.atlassian.net/browse/DFC-63]
To test:
1. Run App
2. Enter url of form page e.g. localhost:3000/organisation-type
3. Journey Guard Page should display
4. Navigate …
=> DFC- 63 - DFC | GA4 | Sandbox | Add journey guard to test pages

package-lock.json, src/app.js, src/config/constants.js, src/validateForm.js, src/views/chooseLocation.njk, src/views/enterEmail.njk, src/views/helpWithHint.njk, src/views/organisationType.njk, src/views/serviceDescription.njk, src/views/summaryPage.njk
(DFC-78)[https://govukverify.atlassian.net/browse/DFC-78]
- Navigate through the journey, click change on the summary page
- Routing added so that a user will navigate back to the summary page on change
- Used a query param to implement this change
=> Dfc 78 dfc ga4 sandbox edit form responses on manage form submission test page

package-lock.json, package.json, src/journeys/chooseLocationService.js, src/journeys/helpWithHintService.js, src/journeys/organisationTypeService.js, src/journeys/serviceDescriptionService.js, src/views/chooseLocation.njk, src/views/enterEmail.njk, src/views/helpWithHint.njk, src/views/organisationType.njk, src/views/serviceDescription.njk, src/views/summaryPage.njk
While testing the Change Response Tracker in the demo app, we discovered a bug. The issue was that the change response tracker wasn't being triggered correctly, as the parameter in the demo app for user to change their form answers is set to "editMode" instead of "edit."
(DFC-163)[https://govukverify.atlassian.net/browse/DFC-163]
=> DFC 163 | Update URL Parameter from "editMode" to "edit" .

package-lock.json, package.json, src/app.js
Demo app needs to use the official analytics package.
(DFC-166)[https://govukverify.atlassian.net/browse/DFC-166]
=> DFC-166: Change analytics package

src/locales/cy/translation.json, src/locales/en/translation.json, src/views/common/base.njk
(DFC-183)[https://govukverify.atlassian.net/browse/DFC-183]
Adds in some extra amendments which will assist the testing plan for navigation
=> Add nav changes

.eslintrc.json, package.json, public/javascript/ua/init.js, src/app.js, src/config/constants.js, src/config/gtmMiddleware.js, src/config/i18next.js, src/config/middleware.js, src/config/nunjucks.js, src/journeys/chooseLocationService.js, src/journeys/enterEmailService.js, src/journeys/helpWithHintService.js, src/journeys/organisationTypeService.js, src/journeys/serviceDescriptionService.js, src/locales/en/translation.json, src/views/characterExample.njk, src/views/common/base.njk
(DFC-184)[https://govukverify.atlassian.net/browse/DFC-184]
- A lot of changes on this PR are linting changes
- Adds a 103 character url to demonstrate what happens if a 100+ url is navigated to
=> Add 120 char url to demo app

src/app.js, src/config/constants.js, src/journeys/feedbackService.js, src/locales/cy/translation.json, src/locales/en/translation.json, src/views/feedback.njk
New form with mutliple of fields:
- dropdown
- free text
- checbox
- radio buttons
(DFC-185)[https://govukverify.atlassian.net/browse/DFC-185]
=> DFC-185: add feedback form

package.json, src/app.js, src/components/language-toggle/package.json, src/views/common/base.njk
(DFC-369)[https://govukverify.atlassian.net/browse/DFC-369]
- correct org name in package.json language toggle
- Update all imports of the language toggle
=> Amend org name and update to latest version

README.md, package-lock.json, package.json, src/views/common/base.njk, test/browser/features/v1/analytics/cookieBanner/cookieBanner.feature, test/browser/features/v1/analytics/ga4/ga4FormChangeEvent.feature, test/browser/features/v1/analytics/ga4/ga4FormErrorEvent.feature, test/browser/features/v1/analytics/ga4/ga4FormReponseEvent.feature, test/browser/features/v1/analytics/ga4/ga4NavigationEvent.feature, test/browser/features/v1/analytics/ga4/ga4PageViewEvent.feature, test/browser/step_definitions/analytics.js, test/browser/step_definitions/common.js, test/browser/step_definitions/cookiePreferences.js, test/browser/step_definitions/cookieSetting.js, test/browser/support/setup.js, test/browser/utils/common.js, test/browser/utils/cookies.js
Add integration tests around Analytics GA4 and cookie banner
(DFC-379)[https://govukverify.atlassian.net/browse/DFC-379]
=> DFC-379: add integration tests

src/components/common-headers/README.md, src/components/common-headers/index.js, src/components/common-headers/package.json, src/components/common-headers/txma-audit-encoded.js
Create a new shared component:
https://www.npmjs.com/package/one-login-common-headers?activeTab=readme
(DCP-3160)[https://govukverify.atlassian.net/browse/DCP-3160]
=> DCP-3160 add common headers middleware component

src/components/common-templates/banner.njk, src/components/common-templates/base-form.njk, src/components/common-templates/base-page.njk, src/components/common-templates/package.json, src/components/common-templates/unrecoverable-error.njk
Copy .njk files from common express and add its into a new component called common-templates
(DFC-481)[https://govukverify.atlassian.net/browse/DFC-481]
=> DFC-481: Add new component common templates

src/components/frontend-language-toggle/package-lock.json, src/components/frontend-language-toggle/package.json
(DFC-**)[https://govukverify.atlassian.net/browse/DFC-**]
=> Release/Language Toggle: v1.0.0 to v1.1.0

src/views/home.njk
This PR adds two details components to the Home Page to test the Details UI tracking that will be integrated into our GA4 analytics package.
(DFC-191)[https://govukverify.atlassian.net/browse/DFC-191]
=> Add details component

src/components/frontend-language-toggle/README.md
Updates the LT readme to reflect package is now in a stable release
(DFC-618)[https://govukverify.atlassian.net/browse/DFC-618]
=> DFC-618(LT): Update readme for stable release

pull_request_template.md
Fixes a typo in the PR template to have the correct link format for tickets
Adds review checklist
=> Chore: Fix typo in PR template
